package cn.cttic.sysframe.frame.domain;

public class SmArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_AREA.AREA_ID
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_AREA.AREA_NAME
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_AREA.PROVINCE_ID
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    private String provinceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_AREA.AREA_ID
     *
     * @return the value of SM_AREA.AREA_ID
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_AREA.AREA_ID
     *
     * @param areaId the value for SM_AREA.AREA_ID
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_AREA.AREA_NAME
     *
     * @return the value of SM_AREA.AREA_NAME
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_AREA.AREA_NAME
     *
     * @param areaName the value for SM_AREA.AREA_NAME
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_AREA.PROVINCE_ID
     *
     * @return the value of SM_AREA.PROVINCE_ID
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_AREA.PROVINCE_ID
     *
     * @param provinceId the value for SM_AREA.PROVINCE_ID
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }
}