package cn.cttic.sysframe.frame.domain;

public class SmCounty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_COUNTY.COUNTY_ID
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    private String countyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_COUNTY.COUNTY_NAME
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    private String countyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_COUNTY.AREA_ID
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    private String areaId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_COUNTY.COUNTY_ID
     *
     * @return the value of SM_COUNTY.COUNTY_ID
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    public String getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_COUNTY.COUNTY_ID
     *
     * @param countyId the value for SM_COUNTY.COUNTY_ID
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    public void setCountyId(String countyId) {
        this.countyId = countyId == null ? null : countyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_COUNTY.COUNTY_NAME
     *
     * @return the value of SM_COUNTY.COUNTY_NAME
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_COUNTY.COUNTY_NAME
     *
     * @param countyName the value for SM_COUNTY.COUNTY_NAME
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_COUNTY.AREA_ID
     *
     * @return the value of SM_COUNTY.AREA_ID
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_COUNTY.AREA_ID
     *
     * @param areaId the value for SM_COUNTY.AREA_ID
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }
}