package cn.cttic.sysframe.frame.domain;

import java.util.Date;

public class SmJobLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_JOB_LOG.LOG_ID
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_JOB_LOG.FILE_ID
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    private Long fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_JOB_LOG.LOG_DESC
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    private String logDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_JOB_LOG.CREATE_DATE
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_JOB_LOG.NOTE
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_JOB_LOG.LOG_ID
     *
     * @return the value of SM_JOB_LOG.LOG_ID
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_JOB_LOG.LOG_ID
     *
     * @param logId the value for SM_JOB_LOG.LOG_ID
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_JOB_LOG.FILE_ID
     *
     * @return the value of SM_JOB_LOG.FILE_ID
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_JOB_LOG.FILE_ID
     *
     * @param fileId the value for SM_JOB_LOG.FILE_ID
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_JOB_LOG.LOG_DESC
     *
     * @return the value of SM_JOB_LOG.LOG_DESC
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    public String getLogDesc() {
        return logDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_JOB_LOG.LOG_DESC
     *
     * @param logDesc the value for SM_JOB_LOG.LOG_DESC
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    public void setLogDesc(String logDesc) {
        this.logDesc = logDesc == null ? null : logDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_JOB_LOG.CREATE_DATE
     *
     * @return the value of SM_JOB_LOG.CREATE_DATE
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_JOB_LOG.CREATE_DATE
     *
     * @param createDate the value for SM_JOB_LOG.CREATE_DATE
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_JOB_LOG.NOTE
     *
     * @return the value of SM_JOB_LOG.NOTE
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_JOB_LOG.NOTE
     *
     * @param note the value for SM_JOB_LOG.NOTE
     *
     * @mbggenerated Fri Apr 04 09:33:38 CST 2014
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}