package cn.cttic.sysframe.frame.domain;

public class SmProvince {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_PROVINCE.PROVINCE_ID
     *
     * @mbggenerated Thu Apr 10 10:57:59 CST 2014
     */
    private String provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_PROVINCE.PROVINCE_NAME
     *
     * @mbggenerated Thu Apr 10 10:57:59 CST 2014
     */
    private String provinceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_PROVINCE.PROVINCE_ID
     *
     * @return the value of SM_PROVINCE.PROVINCE_ID
     *
     * @mbggenerated Thu Apr 10 10:57:59 CST 2014
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_PROVINCE.PROVINCE_ID
     *
     * @param provinceId the value for SM_PROVINCE.PROVINCE_ID
     *
     * @mbggenerated Thu Apr 10 10:57:59 CST 2014
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_PROVINCE.PROVINCE_NAME
     *
     * @return the value of SM_PROVINCE.PROVINCE_NAME
     *
     * @mbggenerated Thu Apr 10 10:57:59 CST 2014
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_PROVINCE.PROVINCE_NAME
     *
     * @param provinceName the value for SM_PROVINCE.PROVINCE_NAME
     *
     * @mbggenerated Thu Apr 10 10:57:59 CST 2014
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }
}