package cn.cttic.sysframe.frame.dao;

import cn.cttic.sysframe.frame.domain.SmArea;
import cn.cttic.sysframe.frame.domain.SmAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_AREA
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    int countByExample(SmAreaExample example);
    
    
    public SmArea selectByPrimaryKey(String areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_AREA
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    int deleteByExample(SmAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_AREA
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    int insert(SmArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_AREA
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    int insertSelective(SmArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_AREA
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    List<SmArea> selectByExample(SmAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_AREA
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    int updateByExampleSelective(@Param("record") SmArea record, @Param("example") SmAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_AREA
     *
     * @mbggenerated Thu Apr 10 10:59:17 CST 2014
     */
    int updateByExample(@Param("record") SmArea record, @Param("example") SmAreaExample example);
}