package cn.cttic.sysframe.frame.dao;

import cn.cttic.sysframe.frame.domain.SmCounty;
import cn.cttic.sysframe.frame.domain.SmCountyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmCountyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_COUNTY
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    int countByExample(SmCountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_COUNTY
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    int deleteByExample(SmCountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_COUNTY
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    int insert(SmCounty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_COUNTY
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    int insertSelective(SmCounty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_COUNTY
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    List<SmCounty> selectByExample(SmCountyExample example);
    
    SmCounty selectByPrimaryKey(String countyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_COUNTY
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    int updateByExampleSelective(@Param("record") SmCounty record, @Param("example") SmCountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_COUNTY
     *
     * @mbggenerated Thu Apr 10 10:59:57 CST 2014
     */
    int updateByExample(@Param("record") SmCounty record, @Param("example") SmCountyExample example);
}