package cn.cttic.sysframe.frame.dao;

import cn.cttic.sysframe.frame.domain.SmTown;
import cn.cttic.sysframe.frame.domain.SmTownExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmTownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TOWN
     *
     * @mbggenerated Thu Apr 10 11:00:29 CST 2014
     */
    int countByExample(SmTownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TOWN
     *
     * @mbggenerated Thu Apr 10 11:00:29 CST 2014
     */
    int deleteByExample(SmTownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TOWN
     *
     * @mbggenerated Thu Apr 10 11:00:29 CST 2014
     */
    int insert(SmTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TOWN
     *
     * @mbggenerated Thu Apr 10 11:00:29 CST 2014
     */
    int insertSelective(SmTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TOWN
     *
     * @mbggenerated Thu Apr 10 11:00:29 CST 2014
     */
    List<SmTown> selectByExample(SmTownExample example);
    
    public SmTown selectByPrimaryKey(String townId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TOWN
     *
     * @mbggenerated Thu Apr 10 11:00:29 CST 2014
     */
    int updateByExampleSelective(@Param("record") SmTown record, @Param("example") SmTownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TOWN
     *
     * @mbggenerated Thu Apr 10 11:00:29 CST 2014
     */
    int updateByExample(@Param("record") SmTown record, @Param("example") SmTownExample example);
}