package cn.cttic.icar.dao;

import cn.cttic.icar.domain.CfgPartType;
import cn.cttic.icar.domain.CfgPartTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgPartTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    int countByExample(CfgPartTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    int deleteByExample(CfgPartTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    int insert(CfgPartType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    int insertSelective(CfgPartType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    List<CfgPartType> selectByExample(CfgPartTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    int updateByExampleSelective(@Param("record") CfgPartType record, @Param("example") CfgPartTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    int updateByExample(@Param("record") CfgPartType record, @Param("example") CfgPartTypeExample example);
}