package cn.cttic.icar.domain;

public class CfgPartType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_part_type.part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    private String partType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_part_type.sys_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    private String sysType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_part_type.sys_sub_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    private String sysSubType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_part_type.sys_part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    private String sysPartType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_part_type.url
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_part_type.part_type
     *
     * @return the value of cfg_part_type.part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    public String getPartType() {
        return partType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_part_type.part_type
     *
     * @param partType the value for cfg_part_type.part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    public void setPartType(String partType) {
        this.partType = partType == null ? null : partType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_part_type.sys_type
     *
     * @return the value of cfg_part_type.sys_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    public String getSysType() {
        return sysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_part_type.sys_type
     *
     * @param sysType the value for cfg_part_type.sys_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    public void setSysType(String sysType) {
        this.sysType = sysType == null ? null : sysType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_part_type.sys_sub_type
     *
     * @return the value of cfg_part_type.sys_sub_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    public String getSysSubType() {
        return sysSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_part_type.sys_sub_type
     *
     * @param sysSubType the value for cfg_part_type.sys_sub_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    public void setSysSubType(String sysSubType) {
        this.sysSubType = sysSubType == null ? null : sysSubType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_part_type.sys_part_type
     *
     * @return the value of cfg_part_type.sys_part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    public String getSysPartType() {
        return sysPartType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_part_type.sys_part_type
     *
     * @param sysPartType the value for cfg_part_type.sys_part_type
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    public void setSysPartType(String sysPartType) {
        this.sysPartType = sysPartType == null ? null : sysPartType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_part_type.url
     *
     * @return the value of cfg_part_type.url
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_part_type.url
     *
     * @param url the value for cfg_part_type.url
     *
     * @mbggenerated Tue Dec 29 15:48:11 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}